trigger:
- master
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build first job 
    - bash: echo $(myPipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build second job 
- stage: DevDeploy
  dependsOn: Build
  variables:
    environment: DEV
    debug: True
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) DevDeploy first job 
- stage: QADeploy
  dependsOn: Build
  variables:
    environment: QA
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) QADeploy first job 
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  variables:
    environment: PROD
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) ProdDeploy first job 
