trigger:
- master
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build first job 
    - bash: echo $(myPipelineLevelVariable)
    - bash: echo $(Agent.MachineName)
    - bash: echo $(Agent.OS)
    - bash: echo $(Environment.Name)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: python --version
    - bash: node --version
    - bash: mvn --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '$(System.DefaultWorkingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
  # - job: SecondJob
  #   steps:
  #   - bash: echo Build second job
# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: DEV
#     debug: True
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment) DevDeploy first job 
# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     environment: QA
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment) QADeploy first job 
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   variables:
#     environment: PROD
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment) ProdDeploy first job 
