trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     macos:
#       operatingSystem: 'macos-latest'

# pool:
#   vmImage: $(operatingSystem)

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - bash: echo Running Build Job...
  - stage: DevDeploy
    jobs:
    - deployment: DevDeployJob
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Running Dev Deployment...
  - stage: QaDeploy
    jobs:
    - deployment: QaDeployJob
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Running Qa Deployment...

