trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello AWS!
  displayName: 'Run a one-line script'

# terraform init backend
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes/'
    backendServiceAWS: 'aws-for-terraform-service-connection'
    backendAWSBucketName: 'terraform-backend-state-moksi20'
    backendAWSKey: 'kubernetes-dev.tfstate'

# terraform apply
